### ISSUE TITLE
CSS variables contain unsupported values

### ISSUE THREAD

**Issue by brycehowitson** [Availity/element#138]
`none` is being produced  as CSS values in the Design Tokens variables. This value is unsupported on multiple attributes and should be 0 (assuming that none is default/unchanged value in Figma).

Current examples:
`--*-letter-spacing: none`
`--*-paragraph-spacing: none`

text-case ( css `text-transform`) has a none value. This is valid but should probably be `initial` instead

**Comment by LauRoxx** [comment]
gotcha. We'll double back with UX to confirm 0 is what is desired for those.
